import { nanoid } from "nanoid";

export const data = [
    {
        taskID: nanoid(),
        title: "Create Project",
        color: "primary",
        paragraphs: [
            {
                id: nanoid(),
                description: "Create react project with npm",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597570,
    },
    {
        taskID: nanoid(),
        title: "Finish Project",
        color: "secondary",
        paragraphs: [
            {
                id: nanoid(),
                description: "Add components",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Test components",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Fix bugs",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597571,
    },
    {
        taskID: nanoid(),
        title: "Deploy Project",
        color: "success",
        paragraphs: [
            {
                id: nanoid(),
                description: "Choose hosting platform",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Setup hosting environment",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Deploy application",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597572,
    },
    {
        taskID: nanoid(),
        title: "Update Project",
        color: "danger",
        paragraphs: [
            {
                id: nanoid(),
                description: "Add new features",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Improve existing features",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Optimize performance",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597573,
    },
    {
        taskID: nanoid(),
        title: "Maintain Project",
        color: "warning",
        paragraphs: [
            {
                id: nanoid(),
                description: "Monitor uptime",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Fix issues",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Update dependencies",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597574,
    },
    {
        taskID: nanoid(),
        title: "Document Project",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Write documentation",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Create tutorials",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Update README",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597575,
    },
    {
        taskID: nanoid(),
        title: "Plan Next Release",
        color: "primary",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify new features",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Prioritize tasks",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Define scope",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597576,
    },
    {
        taskID: nanoid(),
        title: "Meet with Team",
        color: "dark",
        paragraphs: [
            {
                id: nanoid(),
                description: "Schedule meeting",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Prepare agenda",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Conduct meeting",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597577,
    },
    {
        taskID: nanoid(),
        title: "Review Code",
        color: "secondary",
        paragraphs: [
            {
                id: nanoid(),
                description: "Check code quality",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Identify issues",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Provide feedback",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597578,
    },
    {
        taskID: nanoid(),
        title: "Write Tests",
        color: "warning",
        paragraphs: [
            {
                id: nanoid(),
                description: "Create test cases",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Test application",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Refactor code",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597579,
    },
    {
        taskID: nanoid(),
        title: "Fix Bugs",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify bugs",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Reproduce issues",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Debug code",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597580,
    },
    {
        taskID: nanoid(),
        title: "Refactor Code",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify areas to improve",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Simplify code",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Remove duplication",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597581,
    },
    {
        taskID: nanoid(),
        title: "Optimize Performance",
        color: "danger",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify performance bottlenecks",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Improve application speed",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Test optimization",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597582,
    },
    {
        taskID: nanoid(),
        title: "Deploy Application",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Select deployment environment",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Configure deployment settings",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Deploy application",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597583,
    },
    {
        taskID: nanoid(),
        title: "Monitor Application",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Set up monitoring tools",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Monitor application performance",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Identify and resolve issues",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597584,
    },
    {
        taskID: nanoid(),
        title: "Provide Support",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Respond to user inquiries",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Address user concerns",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Resolve user issues",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597585,
    },
    {
        taskID: nanoid(),
        title: "Write Documentation",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Create user guide",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Write API documentation",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Document code",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597586,
    },
    {
        taskID: nanoid(),
        title: "Conduct Code Review",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Review code changes",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Provide feedback to developers",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Ensure code quality",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597587,
    },
    {
        taskID: nanoid(),
        title: "Perform Database Maintenance",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Back up database",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Optimize database performance",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Ensure data integrity",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597588,
    },
    {
        taskID: nanoid(),
        title: "Develop New Features",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify user needs",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Design new features",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Develop and test new features",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597589,
    },
    {
        taskID: nanoid(),
        title: "Create Marketing Materials",
        color: "info",
        paragraphs: [
            {
                id: nanoid(),
                description: "Design marketing materials",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Create content for marketing materials",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Distribute marketing materials",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597590,
    },
    {
        taskID: nanoid(),
        title: "Develop Business Strategy",
        color: "warning",
        paragraphs: [
            {
                id: nanoid(),
                description: "Analyze market trends",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Identify business opportunities",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Develop business strategy",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597591,
    },
    {
        taskID: nanoid(),
        title: "Manage Project Budget",
        color: "secondary",
        paragraphs: [
            {
                id: nanoid(),
                description: "Track project expenses",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Monitor budget vs actuals",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Report on budget status",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597592,
    },
    {
        taskID: nanoid(),
        title: "Recruit New Team Members",
        color: "danger",
        paragraphs: [
            {
                id: nanoid(),
                description: "Identify job requirements",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Post job openings",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Interview and hire candidates",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597593,
    },
    {
        taskID: nanoid(),
        title: "Improve Customer Experience",
        color: "success",
        paragraphs: [
            {
                id: nanoid(),
                description: "Gather customer feedback",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Analyze customer feedback",
                completed: false,
                user: "",
            },
            {
                id: nanoid(),
                description: "Implement improvements",
                completed: false,
                user: "",
            },
        ],
        createdAt: 1681975597594,
    },
];
